apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-depl
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: '2181'
        - name: ZOOKEEPER_TICK_TIME
          value: '2000'
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-sv
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181

