apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-depl
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 29092
        env:
        - name: KAFKA_BROKER_ID
          value: '1'
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'zookeeper-sv:2181'
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: '1'
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: '0'
        - name: CONFLUENT_METRICS_ENABLE
          value: 'false'
        - name: KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: 'true'
        # command: ['sh', '-c']
        # args:
        # - |
        #   sleep 15
        #   kafka-topics --create --topic created-order --bootstrap-server localhost:29092 --replication-factor 1 --partitions 1
        #   kafka-topics --create --topic updated-order --bootstrap-server localhost:29092 --replication-factor 1 --partitions 1
        #   kafka-topics --create --topic completed-order --bootstrap-server localhost:29092 --replication-factor 1 --partitions 1
        #   kafka-topics --create --topic created-payment --bootstrap-server localhost:29092 --replication-factor 1 --partitions 1
        #   kafka-topics --create --topic updated-ticket --bootstrap-server localhost:29092 --replication-factor 1 --partitions 1
        #   kafka-topics --create --topic created-ticket --bootstrap-server localhost:29092 --replication-factor 1 --partitions 1
        #   /etc/confluent/docker/run

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-sv
spec:
  selector:
    app: kafka
  ports:
  - port: 29092
    targetPort: 29092
