apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-depl
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: 'bitnami/redis:latest'
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: 'yes'
        volumeMounts:
        - name: redis-data
          mountPath: /bitnami/redis/data
      restartPolicy: Always
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sv
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379

