apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-depl
spec:
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
      - name: ticket
        image: ticket-service-image
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-sv
spec:
  selector:
    app: ticket
  ports:
  - port: 80
    targetPort: 80

