apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-depl
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: order-service-image
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order-sv
spec:
  selector:
    app: order
  ports:
  - port: 80
    targetPort: 80

