apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-mysql-depl
spec:
  selector:
    matchLabels:
      app: payment-mysql
  template:
    metadata:
      labels:
        app: payment-mysql
    spec:
      containers:
      - name: payment-mysql
        image: mysql/mysql-server:8.0
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: '12345678'
        - name: MYSQL_ROOT_HOST
          value: '%'
        - name: MYSQL_DATABASE
          value: 'robert'
        - name: MYSQL_USER
          value: 'robert'
        - name: MYSQL_PASSWORD
          value: '12345678'
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: '1'
        volumeMounts:
        - name: payment-mysql-data
          mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
      - name: payment-mysql-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: payment-mysql-sv
spec:
  selector:
    app: payment-mysql
  ports:
  - port: 3306
    targetPort: 3306

