apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-depl
spec:
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: payment-service-image
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: payment-sv
spec:
  selector:
    app: payment
  ports:
  - port: 80
    targetPort: 80

